app-django/datavent/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("schedule", views.schedule, name="schedule"),
    path("code-of-conduct", views.code_of_conduct, name="code-of-conduct"),
    path("registration/", include("registration.urls", namespace="registration")),
    path('admin/', admin.site.urls),
]

app-django/registration/urls.py
from django.urls import path

from . import views

app_name = "registration"

urlpatterns = [
    path("", views.index, name="index"),
]

app-django/datavent/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from django.template import loader


def index(request):
    return render(request, "datavent/index.html")


def schedule(request):
    return render(request, "datavent/schedule.html")


def code_of_conduct(request):
    return render(request, "datavent/code-of-conduct.html")

app-django/templates/datavent/base.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ohio North Data Saturday</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'datavent/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'datavent/style.css' %}">
    {% block headscript %}
    {% endblock headscript %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Ohio North Data Saturday</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'index' and request.resolver_match.route == '' %}active{% endif %}" {% if request.resolver_match.url_name == 'index' and request.resolver_match.route == '' %}aria-current="page"{% endif %} href="{% url 'index' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'index' and request.resolver_match.route == 'registration/' %}active{% endif %}" {% if request.resolver_match.url_name == 'index' and request.resolver_match.route == 'registration/' %}aria-current="page"{% endif %} href="{% url 'registration:index' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.url_name == 'schedule' %}active{% endif %}" {% if request.resolver_match.url_name == 'schedule' %}aria-current="page"{% endif %} href="{% url 'schedule' %}">Schedule</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">More...</a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item disabled" href="#">Monthly Meetings</a></li>
                <li><a class="dropdown-item disabled" href="#">FAQs</a></li>
                <li><a class="dropdown-item disabled" href="#">Call for Speakers</a></li>
                <li><a class="dropdown-item disabled" href="#">Sponsorship Plans</a></li>
                <li><a class="dropdown-item" href="{% url 'code-of-conduct' %}">Code of Conduct</a></li>
                <li><a class="dropdown-item disabled" href="#">Contact</a></li>
              </ul>
            </li>
          </ul>
          
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock content %}
    <script src="{% static 'datavent/bootstrap.js' %}"></script>
  </body>
</html>

app-django/templates/datavent/code-of-conduct.html
{% extends 'datavent/base.html' %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
  <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Code of Conduct</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">ONDT events seek to create a respectful, friendly, patient, considerate, and inclusive event experience, and an environment where all participants feel welcome.</p>
      
    <p class="lead mb-4">We therefore ask all participants to honor this Code of Conduct. Any kind of disruptive, intolerant or inappropriate behavior will not be tolerated, and we reserve the right to remove any participants who violate our Code of Conduct from the event.</p>
      
    <p class="lead mb-4">We do not tolerate any harassment or discrimination. Although this list cannot be exhaustive, we explicitly honor diversity in age, gender, gender identity or expression, culture, ethnicity, language, national origin, profession, race, religion, sexual orientation, socioeconomic status, physical and psychological ability, and technical ability.</p>
      
    <p class="lead mb-4">The organizer of this event will prioritize marginalized people’s safety over privileged people’s comfort. Please report any concerns, harassing behavior, suspicious, or disruptive activity to the event organizer or staff.</p>
  </div>
</div>
{% endblock content %}

app-django/templates/datavent/index.html
{% extends 'datavent/base.html' %}

{% block content %}
<div class="px-4 py-5 my-5 text-center">
  <!-- <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57"> -->
  <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Ohio North Data Saturday</h1>
  <h3 class="display-8 fw-bold text-body-emphasis lh-1 mb-3">February 3, 2024</h3>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Data Saturday is a FREE data-focused community conference.</p>
    <p class="lead mb-4">Join us for a full-day of sessions on databases, the cloud, python, and more, as well as network with local data professionals.</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Register Now</button>
    </div>
  </div>
</div>
{% endblock content %}

app-django/templates/datavent/schedule.html
{% extends 'datavent/base.html' %}

{% block content %}

<div class="container">
  <main>
    <script type="text/javascript" src="https://sessionize.com/api/v2/bghcxs7l/view/GridSmart"></script>
  </main>
</div>
{% endblock content %}